### ISSUE TITLE
Train wit with existing data doesn't work

### ISSUE THREAD

**Issue by zhengjunxin** [wit-ai/wit-api-only-tutorial#3]
[demo](https://github.com/zhengjunxin/wit-demo) can reproduce my operations and problems, and am I miss anything?

**Comment by blandinw** [comment]
@kazimanzurrashid is right. This is documented here: https://wit.ai/docs/http/20170307#post--samples-link

![image](https://user-images.githubusercontent.com/413070/29380946-656533a6-827c-11e7-9b8b-1affad52bd8a.png)
