### ISSUE TITLE
/samples endpoint does not work

### ISSUE THREAD

**Issue by kazimanzurrashid** [wit-ai/wit-api-only-tutorial#4]
Whenever I post in /samples endpoint, it accepts, but when visiting wit.ai console, except "intent" no other entities selection get persisted, and interesting the wit.ai console itself does not use this endpoint instead it posts the data in an undocument endpint /sync?verbose=true!

**Comment by blandinw** [comment]
duplicates https://github.com/wit-ai/wit/issues/699
