### ISSUE TITLE
require('../shared')

### ISSUE THREAD

**Issue by danedabomb** [wit-ai/wit-api-only-tutorial#5]
I am currently using this code to migrate my wittyfiddle away from stories. However, the section of code below gives me the error that '../shared' is not a valid module. Is there a way to fix this?

const {
  queryWit,
  interactive,
  firstEntity,
} = require('../shared');

Also, my wittyfiddle code does not recognize interactive(handleMessage). Any help would be much appreciated! :)

Thanks,

Dane

**Comment by stopachka** [comment]
hey @danedabomb -- require('../shared') is used in this demo to reference this file: 

https://github.com/wit-ai/wit-api-only-tutorial/blob/master/shared.js

This would only work if you:
- git clone this repo
- run npm install
- cd into one of the examples
- then run `node {file}.js`

What are you trying to do exactly? If you have a repo and next steps I can take a look at happy to help

**Comment by danedabomb** [comment]
Stepan,

I am trying to migrate my old app in wittyfiddle to respond to /messages
instead of /converse using actions from stories. Here is a snippet of my
wittyfiddle chatbot code:

var messengerSend = require('messengerSend');
var BSUBSCRIBED = true;
var LSUBSCRIBED = true;
var DSUBSCRIBED = true;

// Actions

var actions = {
  send: send,
  subscription: subscription,
  subscriptionBreakfast: subscriptionBreakfast,
  subscriptionLunch: subscriptionLunch,
  subscriptionLunches: subscriptionLunches,
  subscriptionDinner: subscriptionDinner,
  subscriptionDinners: subscriptionDinners,
  cancelbsub: cancelbsub,
  cancellsub: cancellsub,
  canceldsub: canceldsub,
  cancelallsub: cancelallsub,
  reset_context: reset_context,
  setMealType: setMealType,
  getMealDataBreakfast: getMealDataBreakfast,
  getMealDataLunch: getMealDataLunch,
  getMealDataDinner: getMealDataDinner,
  getUOD: getUOD,
  getHaps: getHaps,
  getGym: getGym,
  getBriefingsData2018: getBriefingsData2018,
  getBriefingsData2019: getBriefingsData2019,
  getBriefingsData2020: getBriefingsData2020,
  getBriefingsData2021: getBriefingsData2021
};

function send(request, response) {
  var message = {};
  if (response.text) {
    message.text = response.text;
  }
  if (response.quickreplies) {
    message.quick_replies = response.quickreplies.map(
      function(reply) {
        return {
          content_type: 'text',
          title: reply,
          payload: reply,
        };
      }
    )
  }
  messengerSend({
    recipient: {id: request.fbid},
    message: message,
  });
}


Beneath this code, I have individual functions for each of the actions. I
am trying to use your tutorial to migrate away from stories, but have not
figured out how to respond to /messages once stories is deprecated. Any
help would be much appreciated, as more than 500 people use this current
application for meal, briefing, gym, and uniform information at my college.

Thank you for your time and any advice.

Respectfully,

Dane
