### ISSUE TITLE
How to execute scripts that are part of the tutorial?

### ISSUE THREAD

**Issue by jrlandau** [wit-ai/wit-api-only-tutorial#7]
The first 2 sections of the tutorial can be executed at a Linux command line--I suppose that's obvious.  But loading the spreadsheet requires execution of a script--actually there are 2 scripts--one in the text and one linked.  How is the user to use these scripts?  Is there a particular environment needed to provide the required modules for the linked script?

**Comment by gagan-bansal** [comment]
If you have update `NEW_ACCESS_TOKEN` and `FIREBASE_CONFIG`
Just run the following at shell
```bash
$ node initial-data/index.js
```
It executes the function `validateSamples` explained in README for 'train with existing data'
