### ISSUE TITLE
Open API specification

### ISSUE THREAD

**Issue by franckleveque** [wit-ai/wit-api-only-tutorial#8]
Hi, 

Is there an OpenAPI specification for the http api ? this would let us build other language clients more easily.

Regards,

**Comment by l5t** [comment]
Not sure what you mean exactly. Does https://wit.ai/docs/http/20170307 suffice?

**Comment by franckleveque** [comment]
Hi,

Swagger / OpenApi specifications are a way to describe/document your rest
Api. It is done through a json or yaml file.

What is interesting is the fact they allow the generation of various
clients in different languages to integrate the Api.

You can find more on https://swagger.io

Regards,



Le 16 mars 2018 17:40, "Laurent Landowski" <notifications@github.com> a
écrit :
